//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlympicFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Athlete
    {
        public Athlete()
        {
            this.Medalists = new HashSet<Medalist>();
        }
    
        public int AthleteID { get; set; }
        public string AthleteName { get; set; }
        public int CountryID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Medalist> Medalists { get; set; }
    }
}
