//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlympicFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Athletes = new HashSet<Athlete>();
        }
    
        public int CountryID { get; set; }
        public string CountryAbr { get; set; }
        public string CountryName { get; set; }
        public Nullable<double> CountryPopulation { get; set; }
        public Nullable<double> CountryGDP { get; set; }
    
        public virtual ICollection<Athlete> Athletes { get; set; }
    }
}
