//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlympicFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipline
    {
        public Discipline()
        {
            this.OlympicEvents = new HashSet<OlympicEvent>();
        }
    
        public int DisciplineID { get; set; }
        public string DisciplineName { get; set; }
        public int SportsCategoryID { get; set; }
    
        public virtual SportsCategory SportsCategory { get; set; }
        public virtual ICollection<OlympicEvent> OlympicEvents { get; set; }
    }
}
