//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlympicFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medalist
    {
        public int OlympicMedalID { get; set; }
        public int AthleteID { get; set; }
        public int OlympicGameId { get; set; }
        public int EventID { get; set; }
        public int MedalID { get; set; }
    
        public virtual Athlete Athlete { get; set; }
        public virtual MedalType MedalType { get; set; }
        public virtual OlympicEvent OlympicEvent { get; set; }
        public virtual OlympicGame OlympicGame { get; set; }
    }
}
