//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlympicFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlympicEvent
    {
        public OlympicEvent()
        {
            this.Medalists = new HashSet<Medalist>();
        }
    
        public int EventID { get; set; }
        public string EventName { get; set; }
        public int DisciplineID { get; set; }
        public string Gender { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual ICollection<Medalist> Medalists { get; set; }
    }
}
