//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlympicFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlympicGame
    {
        public OlympicGame()
        {
            this.Medalists = new HashSet<Medalist>();
        }
    
        public int OlympicGameID { get; set; }
        public int Year { get; set; }
        public string HostingCity { get; set; }
        public string Season { get; set; }
    
        public virtual ICollection<Medalist> Medalists { get; set; }
    }
}
