//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlympicFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportsCategory
    {
        public SportsCategory()
        {
            this.Disciplines = new HashSet<Discipline>();
        }
    
        public int SportsCategoryID { get; set; }
        public string SportsCategoryName { get; set; }
    
        public virtual ICollection<Discipline> Disciplines { get; set; }
    }
}
